### ISSUE TITLE
[공지] 설문조사를 실시해주세요.

### ISSUE THREAD

**Issue by unizard** [moduPlayGound/CheetSheet#3]
모놀입학생 여러분 안녕하세요. 1기 여러분의 설문조사를 실시합니다.
다음의 [링크](http://naver.me/xOFJMfbS)로 들어가셔서 설문조사에 성실하게 응해주시기 바랍니다. 😘

http://naver.me/xOFJMfbS

**Comment by unizard** [comment]
설문조사를 마치시면, 본 이슈에 comment 달아주세요.
현재 이정민, 권석준 학생이 설문조사를 하였습니다.

**Comment by kmj0249** [comment]
곽민재 설문조사 제출하였습니다~!

2018년 11월 3일 (토) 오후 5:53, Yukyung Choi <notifications@github.com>님이 작성:

**Comment by MartinusChoi** [comment]
최영민 설문조사 완료했습니다!

**Comment by hyeon9698** [comment]
조동현 설문조사 완료했습니다!

**Comment by 18011780KimMinJun** [comment]
김민준 설문조사 완료했습니다!

**Comment by ghost** [comment]
박진현

설문조사를 완료했습니다.

**Comment by HyeongJo** [comment]
안형조

설문조사를 완료했습니다!!!
